name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore
      working-directory: src
    - name: Build
      run: dotnet build --configuration Release --no-restore
      working-directory: src
    - name: Test
      run: dotnet test --no-restore --verbosity normal
      working-directory: src
    - name: Publish
      run: dotnet publish --verbosity normal --configuration Release --runtime linux-x64 -o ../publish
      working-directory: src
    - name: Archive
      run: tar czf ../gambot.tar.gz .
      working-directory: publish
    - name: Save
      uses: actions/upload-artifact@v2
      with:
        # Artifact name
        name: gambot
        # A file, directory or wildcard pattern that describes what to upload
        path: gambot.tar.gz
    
