name: Publish

on:
  workflow_run:
    workflows: [ ".NET Core" ]
    branches: [ master ]
    types: [ completed ]

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Download the published archive
        uses: actions/download-artifact@v2.0.10
        with:
          name: gambot
      - name: Upload to the server
        uses: appleboy/scp-action@v0.0.1
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USERNAME }}
          password: ${{ secrets.DEPLOY_PASSWORD }}
          port: ${{ secrets.DEPLOY_PORT }}
          source: gambot.tar.gz
          target: ${{ secrets.DEPLOY_TARGET }}
        
